repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format AWSIM.sln --include
        types_or: [ "c#", "vb" ]

# https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/.pre-commit-config.yaml
exclude: >
  (?x)^(
      .*.css|
      .*.meta|
      .*.mat|
      .*.preset|
      .*.lighting|
      .*.dae
      .*.unity
      .*.asset
      .*.prefab
      .*.controller
  )$
