name: buildtest
on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target_platform:
          - StandaloneLinux64
        unity_version:
          - 2021.1.7f1
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ matrix.target_platform }}
        unityVersion: ${{ matrix.unity_version }}
